# Generated by Django 5.1.7 on 2025-08-24 04:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeet', '0002_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(default=django.utils.timezone.now, verbose_name=''),
            preserve_default=False,
        ),
    ]
